kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
      - git fetch origin
    when:
      event: [pull_request, tag]

  - name: test
    image: golang:1.13.4
    volumes:
      - name: deps
        path: /go
    commands:
      - sh ./testdata/setup_test_repos.sh
      - make ci
    when:
      event: [pull_request]
    depends_on: [fetch]

  - name: release
    image: golang:1.13.4
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

  - name: validate-commits
    image: outillage/commitsar:0.9.0
    when:
      event: [pull_request]
    depends_on: [fetch]

  # This is here for backwards compatibility for repos using old naming
  - name: docker-deprecated
    image: plugins/docker
    settings:
      auto_tag: true
      repo: commitsar/release-notary
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      repo: outillage/release-notary
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: release-notes
    image: golang:1.13.4
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GITHUB_REPOSITORY: ${CI_REPO}
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    commands:
      - go run main.go publish
    when:
      event: [tag]

volumes:
  - name: deps
    temp: {}
