kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
      - git fetch origin
    when:
      event: [pull_request, tag]

  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - make ci
    when:
      event: [pull_request]
    depends_on: [fetch]

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

  - name: validate-commits
    image: commitsar/commitsar:0.8.0
    when:
      event: [pull_request]
    depends_on: [fetch]

  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      repo: commitsar/release-notary
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: release-notes
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GITHUB_REPOSITORY: commitsar-app/release-notary
    commands:
      - go run main.go publish
    when:
      event: [tag]

volumes:
  - name: deps
    temp: {}
