language: go
sudo: false
matrix:
  include:
    # "1.x" always refers to the latest Go version, inc. the patch release.
    # e.g. "1.x" is 1.11 until 1.11.1 is available.
    - go: 1.x
      env:
        - LATEST=true
        - GO111MODULE=on
    - go: 1.11.x
    - go: 1.12.x
    - go: tip
  allow_failures:
    - go: tip

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

env:
  - GO111MODULE=on

install: true

script:
  - go mod download
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v -race ./...
  # Only build binaries from the latest Go release.
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="release-notary.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # Your *encrypted* GitHub key, as the output of the Travis CI CLI tool.
    secure: $GITHUB_TOKEN
  file:
    # The names of the binaries to output, based on the -output template passed to gox.
    - release-notary.windows.amd64.exe
    - release-notary.darwin.amd64
    - release-notary.linux.amd64
  on:
    # What to repository to build
    repo: Fallion/release-notary
    # Only build binaries for tagged commits
    tags: true
    condition: $LATEST = true
