name: "Release Notary"
description: "Add Release Notes to your Github releases"
author: "Simon Prochazka"
branding:
  icon: "code"
  color: "blue"
inputs:
  config:
    description: "Path of the Release Notary config file"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
