name: Linters

on: [pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run Commitsar
        uses: docker://aevea/commitsar@sha256:afecf08d41b766273234b09f7c5eb818af979225bad01c268cf5117fdc3f224c
