name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-notary:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Release Notary
        run: go run main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: goreleaser
        uses: docker://goreleaser/goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release
        if: success()

      - name: Kaniko build
        uses: outillage/kaniko-action@master
        with:
          image: outillage/release-notary
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: outillage/cache
          strip_tag_prefix: v
